version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_DIR=/data
    volumes:
      - ./backend:/data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  simulador:
    build:
      context: .
      dockerfile: simulador/Dockerfile
    environment:
      - API_URL=http://backend:5000/sensor
    depends_on:
      - backend

